server:
  port: 7070
spring:
  datasource:
    url: jdbc:mysql://localhost:23306/core_master_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
doma:
  dialect: mysql
  sql-file-repository: no_cache